# Generated by Django 4.0.6 on 2022-07-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAllo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesource',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='imagesource',
            name='task',
        ),
        migrations.AddField(
            model_name='comment',
            name='image_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskAllo.imagesource'),
        ),
        migrations.AddField(
            model_name='task',
            name='image_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskAllo.imagesource'),
        ),
    ]
