# Generated by Django 4.0.6 on 2022-07-24 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAllo', '0003_alter_comment_options_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='team_2',
        ),
        migrations.AddField(
            model_name='connection',
            name='task_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_1', to='TaskAllo.team'),
        ),
        migrations.AddField(
            model_name='connection',
            name='task_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_2', to='TaskAllo.team'),
        ),
    ]
