# Generated by Django 4.0.6 on 2022-08-13 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_task', models.ImageField(upload_to='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status_task', models.TextField(choices=[('Backlog', 'Backlog'), ('Ready to dev', 'Ready To Dev'), ('In progress', 'In Progress'), ('Ready to QA', 'Ready To Qa'), ('Production', 'Production')], default='Backlog', verbose_name='Status task')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(limit_choices_to=models.Q(('role', 'admin'), ('role', 'manager'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('image_task', models.ManyToManyField(blank=True, to='Task.imagetask')),
                ('involved_employees', models.ManyToManyField(blank=True, related_name='involved_employees', to=settings.AUTH_USER_MODEL)),
                ('tasks_connections', models.ManyToManyField(blank=True, to='Task.task')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_team', to='Employees.team')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
